fix: Correct link to provider dev guide in README
crossplane/provider-template pull request #77
Opened 2023-04-24 07:58 UTC by UnseenWizzard

It seems the markdown in the main repo was moved, making the previous link to lead nowhere.

### Description of your changes

Fixes a link in the README

2023-04-25 11:31 UTC, ytsarev approved these changes
Thanks for the catch!

2023-04-25 11:31 UTC, ytsarev requested changes
On a second look, could you please sign your commit with `git commit -s` to comply with DCO ? :)

2023-04-25 19:02 UTC, UnseenWizzard commented
> On a second look, could you please sign your commit with `git commit -s` to comply with DCO ? :)

Sure! I did but, just saw the action didn't like me using a different mail than the noreply.github one on the commit.
Commit is amended :)

2023-04-27 09:21 UTC, ytsarev approved these changes
Thank you!

2023-04-27 09:27 UTC, jbw976 approved these changes

2023-04-27 09:28 UTC, merged